networks:
  app-network:
    driver: bridge
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://musmen:musmen_secret_key@app_database:5432/home_library_service_db?schema=public"
      CHOKIDAR_USEPOLLING: "true"
      NODE_ENV: development
    depends_on:
      - app_database
    networks:
      - app-network
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    restart: on-failure:3
  app_database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "musmen"
      POSTGRES_PASSWORD: "musmen_secret_key"
      POSTGRES_DB: "home_library_service_db"
    networks:
      - app-network
    restart: on-failure:3
